if(NOT DEFINED ASSIMP_LIB_DIR OR ASSIMP_LIB_DIR STREQUAL "")
    message(FATAL_ERROR "ASSIMP_LIB_DIR is required.")
endif()

if(NOT DEFINED ASSIMP_SELECTED_LIB OR ASSIMP_SELECTED_LIB STREQUAL "")
    message(FATAL_ERROR "ASSIMP_SELECTED_LIB is required.")
endif()

set(_candidates)
file(GLOB _vc_candidates "${ASSIMP_LIB_DIR}/assimp-vc*-mt.lib")
list(APPEND _candidates ${_vc_candidates})
file(GLOB _generic_candidates "${ASSIMP_LIB_DIR}/assimp-*-mt.lib")
list(APPEND _candidates ${_generic_candidates})
if(EXISTS "${ASSIMP_LIB_DIR}/assimp.lib")
    list(APPEND _candidates "${ASSIMP_LIB_DIR}/assimp.lib")
endif()

list(REMOVE_DUPLICATES _candidates)
if(_candidates STREQUAL "")
    message(FATAL_ERROR "No assimp static library found in '${ASSIMP_LIB_DIR}'.")
endif()

set(_selected "")
set(_selected_score -1)
foreach(_path IN LISTS _candidates)
    get_filename_component(_name "${_path}" NAME)
    set(_score 0)
    if(_name MATCHES "^assimp-vc([0-9]+)-mt\\.lib$")
        set(_score "${CMAKE_MATCH_1}")
    elseif(_name STREQUAL "assimp.lib")
        set(_score 1)
    else()
        set(_score 10)
    endif()

    if(_score GREATER _selected_score)
        set(_selected_score "${_score}")
        set(_selected "${_path}")
    endif()
endforeach()

if(_selected STREQUAL "")
    message(FATAL_ERROR "Failed to resolve assimp static library from '${ASSIMP_LIB_DIR}'.")
endif()

file(COPY_FILE "${_selected}" "${ASSIMP_SELECTED_LIB}" ONLY_IF_DIFFERENT)
message(STATUS "Resolved assimp static lib: ${_selected} -> ${ASSIMP_SELECTED_LIB}")
